In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

Pass/Fail에 대한 모델링

In [2]:
df = pd.read_csv('data.csv')

In [3]:
df.shape

(1567, 49)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1567 entries, 0 to 1566
Data columns (total 49 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   X20        1567 non-null   float64
 1   X86        1567 non-null   float64
 2   X87        1567 non-null   float64
 3   X88        1567 non-null   float64
 4   X113       1567 non-null   float64
 5   X115       1567 non-null   float64
 6   X116       1567 non-null   float64
 7   X117       1567 non-null   float64
 8   X119       1186 non-null   float64
 9   X120       1567 non-null   float64
 10  X156       1567 non-null   float64
 11  X221       1567 non-null   float64
 12  X222       1567 non-null   float64
 13  X223       1567 non-null   float64
 14  X248       1567 non-null   float64
 15  X250       1567 non-null   float64
 16  X251       1567 non-null   float64
 17  X252       1567 non-null   float64
 18  X254       1567 non-null   float64
 19  X255       1567 non-null   float64
 20  X291       1567 non-null   float64
 21  X359       1567 non-null   float64
 22  X360       1567 non-null   float64
 23  X361       1567 non-null   float64
 24  X386       1567 non-null   float64
 25  X388       1567 non-null   float64
 26  X389       1567 non-null   float64
 27  X390       1567 non-null   float64
 28  X392       1567 non-null   float64
 29  X393       1567 non-null   float64
 30  X429       1567 non-null   float64
 31  X493       1567 non-null   float64
 32  X494       1567 non-null   float64
 33  X495       1567 non-null   float64
 34  X520       1567 non-null   float64
 35  X522       1567 non-null   float64
 36  X523       1567 non-null   float64
 37  X524       1567 non-null   float64
 38  X526       1567 non-null   float64
 39  X527       1567 non-null   float64
 40  X570       1567 non-null   float64
 41  X571       1567 non-null   float64
 42  X572       1567 non-null   float64
 43  X573       1567 non-null   float64
 44  X574       1567 non-null   float64
 45  X575       1567 non-null   float64
 46  X576       1567 non-null   float64
 47  X577       1567 non-null   float64
 48  Pass.Fail  1567 non-null   int64
dtypes: float64(48), int64(1)
memory usage: 600.0 KB

In [5]:
df.describe()

,X20,X86,X87,X88,X113,X115,X116,X117,X119,X120,...,X527,X570,X571,X572,X573,X574,X575,X576,X577,Pass.Fail
count,1567.000000,1567.000000,1567.000000,1567.000000,1567.000000,1567.000000,1567.000000,1567.000000,1186.000000,1567.000000,...,1567.000000,1567.000000,1567.000000,1567.000000,1567.000000,1567.000000,1567.000000,1567.000000,1567.000000,1567.000000
mean,1.405054,2.401872,0.982420,1807.815021,0.945424,747.383792,0.987130,58.625908,0.970696,6.310863,...,6.395717,530.523623,2.101836,28.450165,0.345636,9.162315,0.104729,5.563747,16.642363,0.066369
std,0.016737,0.037332,0.012848,53.537262,0.012133,48.949250,0.009497,6.485174,0.008740,0.124304,...,1.888698,17.499736,0.275112,86.304681,0.248478,26.920150,0.067791,16.921369,12.485267,0.249005
min,1.179700,2.242500,0.774900,1627.471400,0.853400,544.025400,0.890000,52.806800,0.841100,5.125900,...,2.170000,317.196400,0.980200,3.540000,0.066700,1.039500,0.023000,0.663600,4.582000,0.000000
25%,1.396500,2.376850,0.975800,1777.470300,0.938600,721.023000,0.989500,57.978300,0.964800,6.246400,...,4.895450,530.702700,1.982900,7.500000,0.242250,2.567850,0.075100,1.408450,11.501550,0.000000
50%,1.406000,2.403900,0.987400,1809.249200,0.946400,750.861400,0.990500,58.549100,0.969450,6.313600,...,6.410800,532.398200,2.118600,8.650000,0.293400,2.975800,0.089500,1.624500,13.817900,0.000000
75%,1.415000,2.428600,0.989700,1841.873000,0.952300,776.781850,0.990900,59.133900,0.978175,6.375850,...,7.594250,534.356400,2.290650,10.130000,0.366900,3.492500,0.112150,1.902000,17.080900,0.000000
max,1.453400,2.555500,0.993500,2105.182300,0.976300,924.531800,0.992400,311.734400,0.982700,7.522000,...,14.447900,589.508200,2.739500,454.560000,2.196700,170.020400,0.550200,90.423500,96.960100,1.000000

In [6]:
df.head()

,X20,X86,X87,X88,X113,X115,X116,X117,X119,X120,...,X527,X570,X571,X572,X573,X574,X575,X576,X577,Pass.Fail
0,1.4026,2.3895,0.9690,1747.6049,0.9460,748.6115,0.9908,58.4306,0.9804,6.3788,...,6.6926,533.8500,2.1113,8.95,0.3157,3.0624,0.1026,1.6765,14.9509,0
1,1.3825,2.3754,0.9894,1931.6464,0.9425,731.2517,0.9902,58.6680,0.9731,6.5061,...,8.8370,535.0164,2.4335,5.92,0.2653,2.0111,0.0772,1.1065,10.9003,0
2,1.4123,2.4532,0.9880,1685.8514,0.9231,718.5777,0.9899,58.4808,0.9772,6.4527,...,6.4568,535.0245,2.0293,11.21,0.1882,4.0923,0.0640,2.0952,9.2721,1
3,1.4011,2.4004,0.9904,1752.0968,0.9564,709.0867,0.9906,58.6635,0.9761,6.4935,...,6.4865,530.5682,2.0253,9.33,0.1738,2.8971,0.0525,1.7585,8.5831,0
4,1.3888,2.4530,0.9902,1828.3846,0.9424,796.5950,0.9908,58.3858,0.9628,6.3551,...,6.3745,532.0155,2.0275,8.83,0.2224,3.1776,0.0706,1.6597,10.9698,0

결측치 처리

In [7]:
df.isnull().sum()

X20            0
X86            0
X87            0
X88            0
X113           0
X115           0
X116           0
X117           0
X119         381
X120           0
X156           0
X221           0
X222           0
X223           0
X248           0
X250           0
X251           0
X252           0
X254           0
X255           0
X291           0
X359           0
X360           0
X361           0
X386           0
X388           0
X389           0
X390           0
X392           0
X393           0
X429           0
X493           0
X494           0
X495           0
X520           0
X522           0
X523           0
X524           0
X526           0
X527           0
X570           0
X571           0
X572           0
X573           0
X574           0
X575           0
X576           0
X577           0
Pass.Fail      0
dtype: int64

In [8]:
round(df['X119'].mean(),4)

0.9707

In [9]:
df = df.fillna(round(df['X119'].mean(),4))

In [10]:
df.isnull().sum()

X20          0
X86          0
X87          0
X88          0
X113         0
X115         0
X116         0
X117         0
X119         0
X120         0
X156         0
X221         0
X222         0
X223         0
X248         0
X250         0
X251         0
X252         0
X254         0
X255         0
X291         0
X359         0
X360         0
X361         0
X386         0
X388         0
X389         0
X390         0
X392         0
X393         0
X429         0
X493         0
X494         0
X495         0
X520         0
X522         0
X523         0
X524         0
X526         0
X527         0
X570         0
X571         0
X572         0
X573         0
X574         0
X575         0
X576         0
X577         0
Pass.Fail    0
dtype: int64

이상값 처리

In [11]:
df.describe()

,X20,X86,X87,X88,X113,X115,X116,X117,X119,X120,...,X527,X570,X571,X572,X573,X574,X575,X576,X577,Pass.Fail
count,1567.000000,1567.000000,1567.000000,1567.000000,1567.000000,1567.000000,1567.000000,1567.000000,1567.000000,1567.000000,...,1567.000000,1567.000000,1567.000000,1567.000000,1567.000000,1567.000000,1567.000000,1567.000000,1567.000000,1567.000000
mean,1.405054,2.401872,0.982420,1807.815021,0.945424,747.383792,0.987130,58.625908,0.970697,6.310863,...,6.395717,530.523623,2.101836,28.450165,0.345636,9.162315,0.104729,5.563747,16.642363,0.066369
std,0.016737,0.037332,0.012848,53.537262,0.012133,48.949250,0.009497,6.485174,0.007603,0.124304,...,1.888698,17.499736,0.275112,86.304681,0.248478,26.920150,0.067791,16.921369,12.485267,0.249005
min,1.179700,2.242500,0.774900,1627.471400,0.853400,544.025400,0.890000,52.806800,0.841100,5.125900,...,2.170000,317.196400,0.980200,3.540000,0.066700,1.039500,0.023000,0.663600,4.582000,0.000000
25%,1.396500,2.376850,0.975800,1777.470300,0.938600,721.023000,0.989500,57.978300,0.966000,6.246400,...,4.895450,530.702700,1.982900,7.500000,0.242250,2.567850,0.075100,1.408450,11.501550,0.000000
50%,1.406000,2.403900,0.987400,1809.249200,0.946400,750.861400,0.990500,58.549100,0.970700,6.313600,...,6.410800,532.398200,2.118600,8.650000,0.293400,2.975800,0.089500,1.624500,13.817900,0.000000
75%,1.415000,2.428600,0.989700,1841.873000,0.952300,776.781850,0.990900,59.133900,0.976500,6.375850,...,7.594250,534.356400,2.290650,10.130000,0.366900,3.492500,0.112150,1.902000,17.080900,0.000000
max,1.453400,2.555500,0.993500,2105.182300,0.976300,924.531800,0.992400,311.734400,0.982700,7.522000,...,14.447900,589.508200,2.739500,454.560000,2.196700,170.020400,0.550200,90.423500,96.960100,1.000000

In [12]:
df.head()

,X20,X86,X87,X88,X113,X115,X116,X117,X119,X120,...,X527,X570,X571,X572,X573,X574,X575,X576,X577,Pass.Fail
0,1.4026,2.3895,0.9690,1747.6049,0.9460,748.6115,0.9908,58.4306,0.9804,6.3788,...,6.6926,533.8500,2.1113,8.95,0.3157,3.0624,0.1026,1.6765,14.9509,0
1,1.3825,2.3754,0.9894,1931.6464,0.9425,731.2517,0.9902,58.6680,0.9731,6.5061,...,8.8370,535.0164,2.4335,5.92,0.2653,2.0111,0.0772,1.1065,10.9003,0
2,1.4123,2.4532,0.9880,1685.8514,0.9231,718.5777,0.9899,58.4808,0.9772,6.4527,...,6.4568,535.0245,2.0293,11.21,0.1882,4.0923,0.0640,2.0952,9.2721,1
3,1.4011,2.4004,0.9904,1752.0968,0.9564,709.0867,0.9906,58.6635,0.9761,6.4935,...,6.4865,530.5682,2.0253,9.33,0.1738,2.8971,0.0525,1.7585,8.5831,0
4,1.3888,2.4530,0.9902,1828.3846,0.9424,796.5950,0.9908,58.3858,0.9628,6.3551,...,6.3745,532.0155,2.0275,8.83,0.2224,3.1776,0.0706,1.6597,10.9698,0

In [13]:
q1 = df['X20'].quantile(0.25)
q3 = df['X20'].quantile(0.75)
iqr = q3 - q1
iqr

0.01849999999999996

In [ ]:
sns.pairplot(df)
plt.show()